Adding advanced workflows

diff --git a/.github/workflows/release_and_publish.yml b/.github/workflows/release_and_publish.yml
--- a/.github/workflows/release_and_publish.yml
+++ b/.github/workflows/release_and_publish.yml
@@ -6,11 +6,135 @@ on:
       - main
     types:
       - closed
-  workflow_dispatch:
-  repository_dispatch:
 
 jobs:
+  setup:
+    name: 'Setup Application'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node: ['18']
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      - name: Step 0 - 📁 Cache node modules
+        uses: actions/cache@v3
+        id: cache-npm
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: |
+            ~/.npm
+            node_modules
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
+        name: Step 1 - ⚙️ Install Dependencies
+        run: npm install
+
+  validate_linters_and_code_format:
+    needs: setup
+    name: 'Validate Linters and Code Format'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node: ['18']
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      - name: Step 0 - 📁 Cache node modules
+        uses: actions/cache@v3
+        id: cache-npm
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: |
+            ~/.npm
+            node_modules
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 1 - 🧪 Run eslint linter
+        run: npm run eslint:check
+      - name: Step 2 - 🧪🧪 Run prettier
+        run: npm run prettier:check
+
+  tests:
+    needs: validate_linters_and_code_format
+    name: 'Run tests'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node: ['18']
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      - name: Step 0 - 📁 Cache node modules
+        uses: actions/cache@v3
+        id: cache-npm
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: |
+            ~/.npm
+            node_modules
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 1 - 🧪 Run tests
+        run: npm run test
+
   build:
+    needs: tests
+    name: 'Build application bundle'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node: ['18']
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      - name: Step 0 - 📁 Cache node modules
+        uses: actions/cache@v3
+        id: cache-npm
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: |
+            ~/.npm
+            node_modules
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 1 - 📁 Cache build dist
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-build-dist
+        with:
+          path: dist
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 2 - 🛠️ Build application bundle
+        run: |
+          npm run build
+          if [ ! -d "dist" ]; then
+            echo "⚠️ Error: dist folder does not exist."
+            exit 1
+          fi
+
+  release_and_publish:
+    needs: build
+    name: 'Release and Publish'
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -24,35 +148,44 @@ jobs:
         with:
           node-version: 18.x
           registry-url: https://registry.npmjs.org/
-      - name: Step 1 - ⚙️ Setup application
+      - name: Step 0 - 📁 Cache node modules
+        uses: actions/cache@v3
+        id: cache-npm
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: |
+            ~/.npm
+            node_modules
+            dist
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 1 - 📁 Cache build dist
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-build-dist
+        with:
+          path: dist
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+      - name: Step 2 - ⚙️ Setup GitHub Config
         run: |
           git config user.name "🤖 DailyBot"
           git config user.email "ops@dailybot.com"
-          npm install
-      - name: Step 2 - 🧪 Run linter
-        run: npm run eslint:fix
-      - name: Step 3 - 🧪🧪 Run prettier
-        run: npm run prettier:fix
-      - name: Step 4 - 🧪🧪🧪 Run tests
-        run: npm run test
-      - name: Step 5 - 🛠️ Build application bundle
-        run: npm run build
-      - name: Step 6 - 📄 Set GitHub release content "BODY" env var
+      - name: Step 3 - 📄 Set GitHub release content "BODY" env var
         run: |
           bash get_github_release_log.sh
           if [[ ! -f git_logs_output.txt ]]; then
             echo "⚠️ No description found for release body content."
             exit 1
           fi
-      - name: Step 7 -🔄 Prepare release
+      - name: Step 4 -🔄 Prepare release
         run: |
-          git status
-          git add .
-          git commit -am "[🤖 DailyBot] Minor updates on package versions." || echo "[🤖 DailyBot] No changes to commit"
           npm run release
-          git remote -v
           git push --follow-tags origin main
-      - name: Step 8 - 🏷️ Set GitHub release "TAG" env vars
+      - name: Step 5 - 🏷️ Set GitHub release "TAG" env vars
         run: |
           GITHUB_RELEASE_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
           if [[ -z $GITHUB_RELEASE_TAG ]]; then
@@ -62,14 +195,87 @@ jobs:
           echo "::set-env name=GITHUB_RELEASE_TAG::$GITHUB_RELEASE_TAG"
         env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: true
-      - name: Step 9 - 🚀 Publish GitHub release
+      - name: Step 6 - 🚀 Publish GitHub release
         uses: ncipollo/release-action@v1
         with:
           name: Release ${{ env.GITHUB_RELEASE_TAG }}
           tag: ${{ env.GITHUB_RELEASE_TAG }}
           bodyFile: git_logs_output.txt
           token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
-      - name: Step 10 - 🚀🚀 Publish npm package
-        run: npm publish
+      - name: Step 7 - 🚀🚀 Publish npm package
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "⚠️ Error: dist folder does not exist."
+            exit 1
+          fi
+          npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+  cleanup_caches:
+    needs: release_and_publish
+    name: 'Cleanup caches'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step 1 - 🗑️ Trigger cleanup caches workflow
+        run: |
+          curl --location "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
+            --header "Authorization: token ${{ secrets.AUTOMATION_GITHUB_TOKEN }}" \
+            --header "Content-Type: application/json" \
+            --data '{
+                "event_type": "cleanup_caches",
+                "client_payload": {}
+            }'
+
+  notify_on_channel:
+    needs: [setup, validate_linters_and_code_format, tests, build, release_and_publish, cleanup_caches]
+    name: 'Notify on channel'
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Step 1 - 🔔 Send notification on channel
+        env:
+          NEEDS_JSON: ${{ toJSON(needs) }}
+        run: |
+          NOTIFICATION_MESSAGE="*WorkFlow: <https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|$GITHUB_WORKFLOW>*"$'\n'
+          NOTIFICATION_MESSAGE+="*Repository:* $GITHUB_REPOSITORY"$'\n'
+          NOTIFICATION_MESSAGE+="*BRANCH:* $GITHUB_REF_NAME"$'\n'
+          INDEX=1
+          NEEDS_ORDER=("setup" "validate_linters_and_code_format" "tests" "build" "release_and_publish" "cleanup_caches")
+          DEPLOYMENT_SUCCESS="true"
+
+          for key in "${NEEDS_ORDER[@]}"; do
+            RESULT=$(echo "${NEEDS_JSON}" | jq -r ".${key}.result")
+            if [ "$RESULT" == "success" ]; then
+              EMOJI="✅"
+            elif [ "$RESULT" == "failure" ]; then
+              DEPLOYMENT_SUCCESS="false"
+              EMOJI="❌"
+            elif [ "$RESULT" == "skipped" ]; then
+              DEPLOYMENT_SUCCESS="false"
+              EMOJI="⏩"
+            else
+              DEPLOYMENT_SUCCESS="false"
+              EMOJI="❓"
+            fi
+            NOTIFICATION_MESSAGE+="• *Job $INDEX:* $key $EMOJI"$'\n'
+            INDEX=$((INDEX+1))
+          done
+
+          if [ "$DEPLOYMENT_SUCCESS" == "true" ]; then
+            NOTIFICATION_MESSAGE="*🚀 DEPLOYMENT SUCCESS:*"$'\n\n'"$NOTIFICATION_MESSAGE"
+          else
+            NOTIFICATION_MESSAGE="@here *⚠️ DEPLOYMENT FAILED:*"$'\n\n'"$NOTIFICATION_MESSAGE"
+          fi
+
+          JSON_DATA=$(jq -n \
+                        --arg msg "$NOTIFICATION_MESSAGE" \
+                        --arg channel "${{ secrets.DAILYBOT_NOTIFICATION_CHANNEL }}" \
+                        '{message: $msg, target_channels: [$channel]}')
+          curl --location 'https://api.dailybot.com/v1/send-message/' \
+            --header "X-API-KEY: ${{ secrets.DAILYBOT_API_KEY }}" \
+            --header 'Content-Type: application/json' \
+            --data "$JSON_DATA"
